// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/referralcommission"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ReferralCommissionUpdate is the builder for updating ReferralCommission entities.
type ReferralCommissionUpdate struct {
	config
	hooks    []Hook
	mutation *ReferralCommissionMutation
}

// Where appends a list predicates to the ReferralCommissionUpdate builder.
func (_u *ReferralCommissionUpdate) Where(ps ...predicate.ReferralCommission) *ReferralCommissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetReferrerID sets the "referrer_id" field.
func (_u *ReferralCommissionUpdate) SetReferrerID(v int64) *ReferralCommissionUpdate {
	_u.mutation.SetReferrerID(v)
	return _u
}

// SetNillableReferrerID sets the "referrer_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableReferrerID(v *int64) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetReferrerID(*v)
	}
	return _u
}

// SetReferredUserID sets the "referred_user_id" field.
func (_u *ReferralCommissionUpdate) SetReferredUserID(v int64) *ReferralCommissionUpdate {
	_u.mutation.ResetReferredUserID()
	_u.mutation.SetReferredUserID(v)
	return _u
}

// SetNillableReferredUserID sets the "referred_user_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableReferredUserID(v *int64) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetReferredUserID(*v)
	}
	return _u
}

// AddReferredUserID adds value to the "referred_user_id" field.
func (_u *ReferralCommissionUpdate) AddReferredUserID(v int64) *ReferralCommissionUpdate {
	_u.mutation.AddReferredUserID(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *ReferralCommissionUpdate) SetAmount(v float64) *ReferralCommissionUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableAmount(v *float64) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *ReferralCommissionUpdate) AddAmount(v float64) *ReferralCommissionUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetSourceCost sets the "source_cost" field.
func (_u *ReferralCommissionUpdate) SetSourceCost(v float64) *ReferralCommissionUpdate {
	_u.mutation.ResetSourceCost()
	_u.mutation.SetSourceCost(v)
	return _u
}

// SetNillableSourceCost sets the "source_cost" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableSourceCost(v *float64) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetSourceCost(*v)
	}
	return _u
}

// AddSourceCost adds value to the "source_cost" field.
func (_u *ReferralCommissionUpdate) AddSourceCost(v float64) *ReferralCommissionUpdate {
	_u.mutation.AddSourceCost(v)
	return _u
}

// SetCommissionRate sets the "commission_rate" field.
func (_u *ReferralCommissionUpdate) SetCommissionRate(v float64) *ReferralCommissionUpdate {
	_u.mutation.ResetCommissionRate()
	_u.mutation.SetCommissionRate(v)
	return _u
}

// SetNillableCommissionRate sets the "commission_rate" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableCommissionRate(v *float64) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetCommissionRate(*v)
	}
	return _u
}

// AddCommissionRate adds value to the "commission_rate" field.
func (_u *ReferralCommissionUpdate) AddCommissionRate(v float64) *ReferralCommissionUpdate {
	_u.mutation.AddCommissionRate(v)
	return _u
}

// SetReferrer sets the "referrer" edge to the User entity.
func (_u *ReferralCommissionUpdate) SetReferrer(v *User) *ReferralCommissionUpdate {
	return _u.SetReferrerID(v.ID)
}

// Mutation returns the ReferralCommissionMutation object of the builder.
func (_u *ReferralCommissionUpdate) Mutation() *ReferralCommissionMutation {
	return _u.mutation
}

// ClearReferrer clears the "referrer" edge to the User entity.
func (_u *ReferralCommissionUpdate) ClearReferrer() *ReferralCommissionUpdate {
	_u.mutation.ClearReferrer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReferralCommissionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReferralCommissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReferralCommissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReferralCommissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReferralCommissionUpdate) check() error {
	if _u.mutation.ReferrerCleared() && len(_u.mutation.ReferrerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReferralCommission.referrer"`)
	}
	return nil
}

func (_u *ReferralCommissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(referralcommission.Table, referralcommission.Columns, sqlgraph.NewFieldSpec(referralcommission.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ReferredUserID(); ok {
		_spec.SetField(referralcommission.FieldReferredUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReferredUserID(); ok {
		_spec.AddField(referralcommission.FieldReferredUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(referralcommission.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(referralcommission.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SourceCost(); ok {
		_spec.SetField(referralcommission.FieldSourceCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSourceCost(); ok {
		_spec.AddField(referralcommission.FieldSourceCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CommissionRate(); ok {
		_spec.SetField(referralcommission.FieldCommissionRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCommissionRate(); ok {
		_spec.AddField(referralcommission.FieldCommissionRate, field.TypeFloat64, value)
	}
	if _u.mutation.ReferrerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralcommission.ReferrerTable,
			Columns: []string{referralcommission.ReferrerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReferrerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralcommission.ReferrerTable,
			Columns: []string{referralcommission.ReferrerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{referralcommission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReferralCommissionUpdateOne is the builder for updating a single ReferralCommission entity.
type ReferralCommissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReferralCommissionMutation
}

// SetReferrerID sets the "referrer_id" field.
func (_u *ReferralCommissionUpdateOne) SetReferrerID(v int64) *ReferralCommissionUpdateOne {
	_u.mutation.SetReferrerID(v)
	return _u
}

// SetNillableReferrerID sets the "referrer_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableReferrerID(v *int64) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetReferrerID(*v)
	}
	return _u
}

// SetReferredUserID sets the "referred_user_id" field.
func (_u *ReferralCommissionUpdateOne) SetReferredUserID(v int64) *ReferralCommissionUpdateOne {
	_u.mutation.ResetReferredUserID()
	_u.mutation.SetReferredUserID(v)
	return _u
}

// SetNillableReferredUserID sets the "referred_user_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableReferredUserID(v *int64) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetReferredUserID(*v)
	}
	return _u
}

// AddReferredUserID adds value to the "referred_user_id" field.
func (_u *ReferralCommissionUpdateOne) AddReferredUserID(v int64) *ReferralCommissionUpdateOne {
	_u.mutation.AddReferredUserID(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *ReferralCommissionUpdateOne) SetAmount(v float64) *ReferralCommissionUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableAmount(v *float64) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *ReferralCommissionUpdateOne) AddAmount(v float64) *ReferralCommissionUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetSourceCost sets the "source_cost" field.
func (_u *ReferralCommissionUpdateOne) SetSourceCost(v float64) *ReferralCommissionUpdateOne {
	_u.mutation.ResetSourceCost()
	_u.mutation.SetSourceCost(v)
	return _u
}

// SetNillableSourceCost sets the "source_cost" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableSourceCost(v *float64) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetSourceCost(*v)
	}
	return _u
}

// AddSourceCost adds value to the "source_cost" field.
func (_u *ReferralCommissionUpdateOne) AddSourceCost(v float64) *ReferralCommissionUpdateOne {
	_u.mutation.AddSourceCost(v)
	return _u
}

// SetCommissionRate sets the "commission_rate" field.
func (_u *ReferralCommissionUpdateOne) SetCommissionRate(v float64) *ReferralCommissionUpdateOne {
	_u.mutation.ResetCommissionRate()
	_u.mutation.SetCommissionRate(v)
	return _u
}

// SetNillableCommissionRate sets the "commission_rate" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableCommissionRate(v *float64) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetCommissionRate(*v)
	}
	return _u
}

// AddCommissionRate adds value to the "commission_rate" field.
func (_u *ReferralCommissionUpdateOne) AddCommissionRate(v float64) *ReferralCommissionUpdateOne {
	_u.mutation.AddCommissionRate(v)
	return _u
}

// SetReferrer sets the "referrer" edge to the User entity.
func (_u *ReferralCommissionUpdateOne) SetReferrer(v *User) *ReferralCommissionUpdateOne {
	return _u.SetReferrerID(v.ID)
}

// Mutation returns the ReferralCommissionMutation object of the builder.
func (_u *ReferralCommissionUpdateOne) Mutation() *ReferralCommissionMutation {
	return _u.mutation
}

// ClearReferrer clears the "referrer" edge to the User entity.
func (_u *ReferralCommissionUpdateOne) ClearReferrer() *ReferralCommissionUpdateOne {
	_u.mutation.ClearReferrer()
	return _u
}

// Where appends a list predicates to the ReferralCommissionUpdate builder.
func (_u *ReferralCommissionUpdateOne) Where(ps ...predicate.ReferralCommission) *ReferralCommissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReferralCommissionUpdateOne) Select(field string, fields ...string) *ReferralCommissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReferralCommission entity.
func (_u *ReferralCommissionUpdateOne) Save(ctx context.Context) (*ReferralCommission, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReferralCommissionUpdateOne) SaveX(ctx context.Context) *ReferralCommission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReferralCommissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReferralCommissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReferralCommissionUpdateOne) check() error {
	if _u.mutation.ReferrerCleared() && len(_u.mutation.ReferrerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReferralCommission.referrer"`)
	}
	return nil
}

func (_u *ReferralCommissionUpdateOne) sqlSave(ctx context.Context) (_node *ReferralCommission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(referralcommission.Table, referralcommission.Columns, sqlgraph.NewFieldSpec(referralcommission.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReferralCommission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, referralcommission.FieldID)
		for _, f := range fields {
			if !referralcommission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != referralcommission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ReferredUserID(); ok {
		_spec.SetField(referralcommission.FieldReferredUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReferredUserID(); ok {
		_spec.AddField(referralcommission.FieldReferredUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(referralcommission.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(referralcommission.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SourceCost(); ok {
		_spec.SetField(referralcommission.FieldSourceCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSourceCost(); ok {
		_spec.AddField(referralcommission.FieldSourceCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CommissionRate(); ok {
		_spec.SetField(referralcommission.FieldCommissionRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCommissionRate(); ok {
		_spec.AddField(referralcommission.FieldCommissionRate, field.TypeFloat64, value)
	}
	if _u.mutation.ReferrerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralcommission.ReferrerTable,
			Columns: []string{referralcommission.ReferrerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReferrerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   referralcommission.ReferrerTable,
			Columns: []string{referralcommission.ReferrerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ReferralCommission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{referralcommission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
