// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/referralcommission"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ReferralCommission is the model entity for the ReferralCommission schema.
type ReferralCommission struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 获得返佣的推荐人
	ReferrerID int64 `json:"referrer_id,omitempty"`
	// 产生消费的被推荐用户
	ReferredUserID int64 `json:"referred_user_id,omitempty"`
	// 返佣金额
	Amount float64 `json:"amount,omitempty"`
	// 触发返佣的原始消费金额
	SourceCost float64 `json:"source_cost,omitempty"`
	// 记录时的返佣比例
	CommissionRate float64 `json:"commission_rate,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReferralCommissionQuery when eager-loading is set.
	Edges        ReferralCommissionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ReferralCommissionEdges holds the relations/edges for other nodes in the graph.
type ReferralCommissionEdges struct {
	// Referrer holds the value of the referrer edge.
	Referrer *User `json:"referrer,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ReferrerOrErr returns the Referrer value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReferralCommissionEdges) ReferrerOrErr() (*User, error) {
	if e.Referrer != nil {
		return e.Referrer, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "referrer"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReferralCommission) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case referralcommission.FieldAmount, referralcommission.FieldSourceCost, referralcommission.FieldCommissionRate:
			values[i] = new(sql.NullFloat64)
		case referralcommission.FieldID, referralcommission.FieldReferrerID, referralcommission.FieldReferredUserID:
			values[i] = new(sql.NullInt64)
		case referralcommission.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReferralCommission fields.
func (_m *ReferralCommission) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case referralcommission.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case referralcommission.FieldReferrerID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field referrer_id", values[i])
			} else if value.Valid {
				_m.ReferrerID = value.Int64
			}
		case referralcommission.FieldReferredUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field referred_user_id", values[i])
			} else if value.Valid {
				_m.ReferredUserID = value.Int64
			}
		case referralcommission.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case referralcommission.FieldSourceCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field source_cost", values[i])
			} else if value.Valid {
				_m.SourceCost = value.Float64
			}
		case referralcommission.FieldCommissionRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field commission_rate", values[i])
			} else if value.Valid {
				_m.CommissionRate = value.Float64
			}
		case referralcommission.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReferralCommission.
// This includes values selected through modifiers, order, etc.
func (_m *ReferralCommission) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryReferrer queries the "referrer" edge of the ReferralCommission entity.
func (_m *ReferralCommission) QueryReferrer() *UserQuery {
	return NewReferralCommissionClient(_m.config).QueryReferrer(_m)
}

// Update returns a builder for updating this ReferralCommission.
// Note that you need to call ReferralCommission.Unwrap() before calling this method if this ReferralCommission
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ReferralCommission) Update() *ReferralCommissionUpdateOne {
	return NewReferralCommissionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ReferralCommission entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ReferralCommission) Unwrap() *ReferralCommission {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReferralCommission is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ReferralCommission) String() string {
	var builder strings.Builder
	builder.WriteString("ReferralCommission(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("referrer_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReferrerID))
	builder.WriteString(", ")
	builder.WriteString("referred_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReferredUserID))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("source_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.SourceCost))
	builder.WriteString(", ")
	builder.WriteString("commission_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.CommissionRate))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ReferralCommissions is a parsable slice of ReferralCommission.
type ReferralCommissions []*ReferralCommission
