// Code generated by ent, DO NOT EDIT.

package referralcommission

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the referralcommission type in the database.
	Label = "referral_commission"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldReferrerID holds the string denoting the referrer_id field in the database.
	FieldReferrerID = "referrer_id"
	// FieldReferredUserID holds the string denoting the referred_user_id field in the database.
	FieldReferredUserID = "referred_user_id"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldSourceCost holds the string denoting the source_cost field in the database.
	FieldSourceCost = "source_cost"
	// FieldCommissionRate holds the string denoting the commission_rate field in the database.
	FieldCommissionRate = "commission_rate"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeReferrer holds the string denoting the referrer edge name in mutations.
	EdgeReferrer = "referrer"
	// Table holds the table name of the referralcommission in the database.
	Table = "referral_commissions"
	// ReferrerTable is the table that holds the referrer relation/edge.
	ReferrerTable = "referral_commissions"
	// ReferrerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ReferrerInverseTable = "users"
	// ReferrerColumn is the table column denoting the referrer relation/edge.
	ReferrerColumn = "referrer_id"
)

// Columns holds all SQL columns for referralcommission fields.
var Columns = []string{
	FieldID,
	FieldReferrerID,
	FieldReferredUserID,
	FieldAmount,
	FieldSourceCost,
	FieldCommissionRate,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultAmount holds the default value on creation for the "amount" field.
	DefaultAmount float64
	// DefaultSourceCost holds the default value on creation for the "source_cost" field.
	DefaultSourceCost float64
	// DefaultCommissionRate holds the default value on creation for the "commission_rate" field.
	DefaultCommissionRate float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ReferralCommission queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByReferrerID orders the results by the referrer_id field.
func ByReferrerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferrerID, opts...).ToFunc()
}

// ByReferredUserID orders the results by the referred_user_id field.
func ByReferredUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferredUserID, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// BySourceCost orders the results by the source_cost field.
func BySourceCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceCost, opts...).ToFunc()
}

// ByCommissionRate orders the results by the commission_rate field.
func ByCommissionRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommissionRate, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByReferrerField orders the results by referrer field.
func ByReferrerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReferrerStep(), sql.OrderByField(field, opts...))
	}
}
func newReferrerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReferrerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ReferrerTable, ReferrerColumn),
	)
}
