// Code generated by ent, DO NOT EDIT.

package referralcommission

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldID, id))
}

// ReferrerID applies equality check predicate on the "referrer_id" field. It's identical to ReferrerIDEQ.
func ReferrerID(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldReferrerID, v))
}

// ReferredUserID applies equality check predicate on the "referred_user_id" field. It's identical to ReferredUserIDEQ.
func ReferredUserID(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldReferredUserID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldAmount, v))
}

// SourceCost applies equality check predicate on the "source_cost" field. It's identical to SourceCostEQ.
func SourceCost(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldSourceCost, v))
}

// CommissionRate applies equality check predicate on the "commission_rate" field. It's identical to CommissionRateEQ.
func CommissionRate(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldCommissionRate, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldCreatedAt, v))
}

// ReferrerIDEQ applies the EQ predicate on the "referrer_id" field.
func ReferrerIDEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldReferrerID, v))
}

// ReferrerIDNEQ applies the NEQ predicate on the "referrer_id" field.
func ReferrerIDNEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldReferrerID, v))
}

// ReferrerIDIn applies the In predicate on the "referrer_id" field.
func ReferrerIDIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldReferrerID, vs...))
}

// ReferrerIDNotIn applies the NotIn predicate on the "referrer_id" field.
func ReferrerIDNotIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldReferrerID, vs...))
}

// ReferredUserIDEQ applies the EQ predicate on the "referred_user_id" field.
func ReferredUserIDEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldReferredUserID, v))
}

// ReferredUserIDNEQ applies the NEQ predicate on the "referred_user_id" field.
func ReferredUserIDNEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldReferredUserID, v))
}

// ReferredUserIDIn applies the In predicate on the "referred_user_id" field.
func ReferredUserIDIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldReferredUserID, vs...))
}

// ReferredUserIDNotIn applies the NotIn predicate on the "referred_user_id" field.
func ReferredUserIDNotIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldReferredUserID, vs...))
}

// ReferredUserIDGT applies the GT predicate on the "referred_user_id" field.
func ReferredUserIDGT(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldReferredUserID, v))
}

// ReferredUserIDGTE applies the GTE predicate on the "referred_user_id" field.
func ReferredUserIDGTE(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldReferredUserID, v))
}

// ReferredUserIDLT applies the LT predicate on the "referred_user_id" field.
func ReferredUserIDLT(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldReferredUserID, v))
}

// ReferredUserIDLTE applies the LTE predicate on the "referred_user_id" field.
func ReferredUserIDLTE(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldReferredUserID, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldAmount, v))
}

// SourceCostEQ applies the EQ predicate on the "source_cost" field.
func SourceCostEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldSourceCost, v))
}

// SourceCostNEQ applies the NEQ predicate on the "source_cost" field.
func SourceCostNEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldSourceCost, v))
}

// SourceCostIn applies the In predicate on the "source_cost" field.
func SourceCostIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldSourceCost, vs...))
}

// SourceCostNotIn applies the NotIn predicate on the "source_cost" field.
func SourceCostNotIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldSourceCost, vs...))
}

// SourceCostGT applies the GT predicate on the "source_cost" field.
func SourceCostGT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldSourceCost, v))
}

// SourceCostGTE applies the GTE predicate on the "source_cost" field.
func SourceCostGTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldSourceCost, v))
}

// SourceCostLT applies the LT predicate on the "source_cost" field.
func SourceCostLT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldSourceCost, v))
}

// SourceCostLTE applies the LTE predicate on the "source_cost" field.
func SourceCostLTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldSourceCost, v))
}

// CommissionRateEQ applies the EQ predicate on the "commission_rate" field.
func CommissionRateEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldCommissionRate, v))
}

// CommissionRateNEQ applies the NEQ predicate on the "commission_rate" field.
func CommissionRateNEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldCommissionRate, v))
}

// CommissionRateIn applies the In predicate on the "commission_rate" field.
func CommissionRateIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldCommissionRate, vs...))
}

// CommissionRateNotIn applies the NotIn predicate on the "commission_rate" field.
func CommissionRateNotIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldCommissionRate, vs...))
}

// CommissionRateGT applies the GT predicate on the "commission_rate" field.
func CommissionRateGT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldCommissionRate, v))
}

// CommissionRateGTE applies the GTE predicate on the "commission_rate" field.
func CommissionRateGTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldCommissionRate, v))
}

// CommissionRateLT applies the LT predicate on the "commission_rate" field.
func CommissionRateLT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldCommissionRate, v))
}

// CommissionRateLTE applies the LTE predicate on the "commission_rate" field.
func CommissionRateLTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldCommissionRate, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldCreatedAt, v))
}

// HasReferrer applies the HasEdge predicate on the "referrer" edge.
func HasReferrer() predicate.ReferralCommission {
	return predicate.ReferralCommission(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ReferrerTable, ReferrerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReferrerWith applies the HasEdge predicate on the "referrer" edge with a given conditions (other predicates).
func HasReferrerWith(preds ...predicate.User) predicate.ReferralCommission {
	return predicate.ReferralCommission(func(s *sql.Selector) {
		step := newReferrerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ReferralCommission) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ReferralCommission) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ReferralCommission) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.NotPredicates(p))
}
